# setwd("/Users/jacobherbstman/Desktop/aldermanic_privilege/tasks/download_parcel_universe_data/code")
# input_csv <- "../temp/parcel_universe_2025_city_native.csv"
# output_csv <- "../output/parcel_universe_2025_city.csv"

source("../../setup_environment/code/packages.R")

cli_args <- commandArgs(trailingOnly = TRUE)
if (length(cli_args) == 0) {
  cli_args <- c(input_csv, output_csv)
}

if (length(cli_args) != 2) {
  stop("FATAL: Script requires 2 args: <input_csv> <output_csv>", call. = FALSE)
}
input_csv <- cli_args[1]
output_csv <- cli_args[2]

native_names <- strsplit(
  "pin,pin10,year,class,triad_name,triad_code,township_name,township_code,nbhd_code,tax_code,zip_code,lon,lat,x_3435,y_3435,census_block_group_geoid,census_block_geoid,census_congressional_district_geoid,census_congressional_district_num,census_county_subdivision_geoid,census_place_geoid,census_puma_geoid,census_school_district_elementary_geoid,census_school_district_secondary_geoid,census_school_district_unified_geoid,census_state_representative_geoid,census_state_representative_num,census_state_senate_geoid,census_state_senate_num,census_tract_geoid,census_zcta_geoid,census_data_year,census_acs5_congressional_district_geoid,census_acs5_congressional_district_num,census_acs5_county_subdivision_geoid,census_acs5_place_geoid,census_acs5_puma_geoid,census_acs5_school_district_elementary_geoid,census_acs5_school_district_secondary_geoid,census_acs5_school_district_unified_geoid,census_acs5_state_representative_geoid,census_acs5_state_representative_num,census_acs5_state_senate_geoid,census_acs5_state_senate_num,census_acs5_tract_geoid,census_acs5_data_year,cook_board_of_review_district_num,cook_board_of_review_district_data_year,cook_commissioner_district_num,cook_commissioner_district_data_year,cook_judicial_district_num,cook_judicial_district_data_year,cook_municipality_num,cook_municipality_name,cook_municipality_data_year,ward_num,ward_chicago_data_year,ward_evanston_data_year,chicago_community_area_num,chicago_community_area_name,chicago_community_area_data_year,chicago_industrial_corridor_num,chicago_industrial_corridor_name,chicago_industrial_corridor_data_year,chicago_police_district_num,chicago_police_district_data_year,econ_coordinated_care_area_num,econ_coordinated_care_area_data_year,econ_enterprise_zone_num,econ_enterprise_zone_data_year,econ_industrial_growth_zone_num,econ_industrial_growth_zone_data_year,econ_qualified_opportunity_zone_num,econ_qualified_opportunity_zone_data_year,econ_central_business_district_num,econ_central_business_district_data_year,env_flood_fema_sfha,env_flood_fema_data_year,env_flood_fs_factor,env_flood_fs_risk_direction,env_flood_fs_data_year,env_ohare_noise_contour_no_buffer_bool,env_ohare_noise_contour_half_mile_buffer_bool,env_ohare_noise_contour_data_year,env_airport_noise_dnl,env_airport_noise_data_year,school_elementary_district_geoid,school_elementary_district_name,school_secondary_district_geoid,school_secondary_district_name,school_unified_district_geoid,school_unified_district_name,school_school_year,school_data_year,tax_municipality_num,tax_municipality_name,tax_school_elementary_district_num,tax_school_elementary_district_name,tax_school_secondary_district_num,tax_school_secondary_district_name,tax_school_unified_district_num,tax_school_unified_district_name,tax_community_college_district_num,tax_community_college_district_name,tax_fire_protection_district_num,tax_fire_protection_district_name,tax_library_district_num,tax_library_district_name,tax_park_district_num,tax_park_district_name,tax_sanitation_district_num,tax_sanitation_district_name,tax_special_service_area_num,tax_special_service_area_name,tax_tif_district_num,tax_tif_district_name,tax_data_year,access_cmap_walk_id,access_cmap_walk_nta_score,access_cmap_walk_total_score,access_cmap_walk_data_year,misc_subdivision_id,misc_subdivision_data_year,row_id",
  ",",
  fixed = TRUE
)[[1]]

legacy_names <- strsplit(
  "pin,pin10,tax_year,class,triad_name,triad_code,township_name,township_code,neighborhood_code,tax_district_code,zip_code,longitude,latitude,centroid_x_crs_3435,centroid_y_crs_3435,census_block_group_geoid,census_block_geoid,census_congressional_district_geoid,census_congressional_district_num,census_county_subdivision_geoid,census_place_geoid,census_puma_geoid,census_school_district_elementary_geoid,census_school_district_secondary_geoid,census_school_district_unified_geoid,census_state_representative_geoid,census_state_representative_num,census_state_senate_geoid,census_state_senate_num,census_tract_geoid,census_zcta_geoid,census_data_year,census_acs5_congressional_district_geoid,census_acs5_congressional_district_num,census_acs5_county_subdivision_geoid,census_acs5_place_geoid,census_acs5_puma_geoid,census_acs5_school_district_elementary_geoid,census_acs5_school_district_secondary_geoid,census_acs5_school_district_unified_geoid,census_acs5_state_representative_geoid,census_acs5_state_representative_num,census_acs5_state_senate_geoid,census_acs5_state_senate_num,census_acs5_tract_geoid,census_acs5_data_year,board_of_review_district_num,board_of_review_district_data_year,commissioner_district_num,commissioner_district_data_year,judicial_district_num,judicial_district_data_year,municipality_num,municipality_name,municipality_data_year,ward_num,ward_chicago_data_year,ward_evanston_data_year,chicago_community_area_num,chicago_community_area_name,chicago_community_area_data_year,chicago_industrial_corridor_num,chicago_industrial_corridor_name,chicago_industrial_corridor_data_year,chicago_police_district_num,chicago_police_district_data_year,coordinated_care_area_num,coordinated_care_area_data_year,enterprise_zone_num,enterprise_zone_data_year,industrial_growth_zone_num,industrial_growth_zone_data_year,qualified_opportunity_zone_num,qualified_opportunity_zone_data_year,central_business_district_num,central_business_district_data_year,flood_fema_sfha,flood_fema_data_year,flood_fs_factor,flood_fs_risk_direction,flood_fs_data_year,ohare_noise_contour_no_buffer_bool,ohare_noise_contour_half_mile_buffer_bool,ohare_noise_contour_data_year,airport_noise_dnl,airport_noise_data_year,school_elementary_district_geoid,school_elementary_district_name,school_secondary_district_geoid,school_secondary_district_name,school_unified_district_geoid,school_unified_district_name,school_year,school_data_year,tax_municipality_num,tax_municipality_name,tax_school_elementary_district_num,tax_school_elementary_district_name,tax_school_secondary_district_num,tax_school_secondary_district_name,tax_school_unified_district_num,tax_school_unified_district_name,tax_community_college_district_num,tax_community_college_district_name,tax_fire_protection_district_num,tax_fire_protection_district_name,tax_library_district_num,tax_library_district_name,tax_park_district_num,tax_park_district_name,tax_sanitation_district_num,tax_sanitation_district_name,tax_special_service_area_num,tax_special_service_area_name,tax_tif_district_num,tax_tif_district_name,tax_districts_data_year,cmap_walkability_grid_id,cmap_walkability_no_transit_score,cmap_walkability_total_score,cmap_walkability_data_year,subdivision_id,subdivision_data_year,row_id",
  ",",
  fixed = TRUE
)[[1]]

parcel_universe <- fread(input_csv, colClasses = "character")
missing_cols <- setdiff(native_names, names(parcel_universe))
if (length(missing_cols) > 0) {
  stop(
    sprintf("Parcel universe API output is missing expected columns: %s", paste(missing_cols, collapse = ", ")),
    call. = FALSE
  )
}

parcel_universe <- parcel_universe[, ..native_names]
setnames(parcel_universe, native_names, legacy_names)
fwrite(parcel_universe, output_csv)
