all: ../output/remaining_home_parcels_2018.geojson ../output/remaining_home_parcels_2019.geojson ../output/remaining_home_parcels_2025.geojson

../output/remaining_home_parcels_2018.geojson: remaining_review_sources.make | ../output ../temp
	curl --fail --location --get 'https://gis.cookcountyil.gov/traditional/rest/services/parcelHistorical/MapServer/20/query' --data-urlencode "where=PIN10 IN ('2023213097','2023213098')" --data-urlencode 'outFields=*' --data-urlencode 'returnGeometry=true' --data-urlencode 'outSR=4326' --data-urlencode 'f=geojson' --output ../temp/remaining_home_parcels_2018.geojson && python3 -c 'import json; d=json.load(open("../temp/remaining_home_parcels_2018.geojson")); assert d["type"]=="FeatureCollection" and not d.get("exceededTransferLimit", False); assert len(d["features"])==2; assert all(f["geometry"] for f in d["features"])' && mv ../temp/remaining_home_parcels_2018.geojson $@

../output/remaining_home_parcels_2019.geojson: remaining_review_sources.make | ../output ../temp
	curl --fail --location --get 'https://gis.cookcountyil.gov/traditional/rest/services/parcelHistorical/MapServer/21/query' --data-urlencode "where=PIN10 IN ('2023213110','2023213111')" --data-urlencode 'outFields=*' --data-urlencode 'returnGeometry=true' --data-urlencode 'outSR=4326' --data-urlencode 'f=geojson' --output ../temp/remaining_home_parcels_2019.geojson && python3 -c 'import json; d=json.load(open("../temp/remaining_home_parcels_2019.geojson")); assert d["type"]=="FeatureCollection" and not d.get("exceededTransferLimit", False); assert len(d["features"])==2; assert all(f["geometry"] for f in d["features"])' && mv ../temp/remaining_home_parcels_2019.geojson $@

../output/remaining_home_parcels_2025.geojson: remaining_review_sources.make | ../output ../temp
	curl --fail --location --get 'https://gis.cookcountyil.gov/traditional/rest/services/parcelHistorical/MapServer/2025/query' --data-urlencode "where=PIN10 IN ('2003400084','2003400085','2003400086','2003400087','2003400088','1428319116','1428319117')" --data-urlencode 'outFields=*' --data-urlencode 'returnGeometry=true' --data-urlencode 'outSR=4326' --data-urlencode 'f=geojson' --output ../temp/remaining_home_parcels_2025.geojson && python3 -c 'import json; d=json.load(open("../temp/remaining_home_parcels_2025.geojson")); assert d["type"]=="FeatureCollection" and not d.get("exceededTransferLimit", False); assert len(d["features"])==7; assert all(f["geometry"] for f in d["features"])' && mv ../temp/remaining_home_parcels_2025.geojson $@
