#!/usr/bin/env python3

import csv
import subprocess
from collections import Counter
from pathlib import Path


OUTPUT = Path("../output")
LEDGER = OUTPUT / "manuscript_code_claim_ledger.csv"
REPORT = OUTPUT / "paper_code_audit_report.md"


rows = []


def add(
    finding_id,
    severity,
    area,
    status,
    manuscript_location,
    production_evidence,
    claim_or_check,
    audit_result,
    estimate_consequence,
    recommended_action,
    audit_evidence,
):
    rows.append(
        {
            "finding_id": finding_id,
            "severity": severity,
            "area": area,
            "status": status,
            "manuscript_location": manuscript_location,
            "production_evidence": production_evidence,
            "claim_or_check": claim_or_check,
            "audit_result": audit_result,
            "estimate_consequence": estimate_consequence,
            "recommended_action": recommended_action,
            "audit_evidence": audit_evidence,
        }
    )


# Institutional setting and interpretation
add("I01", "Pass", "Institution", "verified", "intro.tex:13", "create_alderman_data outputs", "Chicago has 50 aldermen.", "The alderman panel contains 50 wards in each relevant map era.", "None.", "No change.", "manuscript_line_inventory.csv")
add("I02", "Pass", "Institution", "verified externally", "intro.tex:14", "Not a production-code claim", "Chicago has no city charter.", "Verified against Chicago institutional sources reviewed during the audit.", "None.", "Retain with a suitable institutional citation.", "institutional source review")
add("I03", "Medium", "Institution", "wording stronger than evidence", "intro.tex:13-17; conclusion.tex:7", "Not a production-code claim", "Each alderman can unilaterally block or approve development.", "The deference norm is well documented, but 'unilaterally' is a strong shorthand for informal influence rather than a literal formal power over every permit.", "Interpretive, not numerical.", "Qualify the institutional description after the empirical pipeline is resolved.", "institutional source review")
add("I04", "High", "Institution", "factual mismatch", "data.tex:27-35", "Historical MCC section 13-32-030", "Projects above a threshold required an aldermanic acknowledgement letter and a 10-day hold.", "The former code imposed a general 10-day aldermanic notice period with limited exceptions. The acknowledgement letter was optional and could permit issuance during the notice period; it was not a threshold-based letter requirement.", "Does not change estimates, but misstates the paper's central institutional mechanism.", "Rewrite this paragraph from the ordinance text and cite the code provision directly.", "institutional source review")
add("I05", "High", "Institution", "factual conflation", "data.tex:43-48", "Historical code and Executive Order 2019-2", "The Lightfoot executive order eliminated the formal permit hold.", "The general Title 13 notice provision was repealed effective July 1, 2019, while Executive Order 2019-2 was signed May 20, 2019. The manuscript conflates distinct legal actions.", "No estimate effect; material institutional precision issue.", "Separate the code repeal from the executive order and scope each claim.", "institutional source review")
add("I06", "Medium", "Institution", "overbroad wording", "data.tex:43-48", "Titles 10, 14A, and 17 review", "The formal aldermanic hold was eliminated.", "The broad former building-permit notice provision ended, but aldermanic notice or hold provisions remained in other contexts. The statement needs to be scoped to the general Department of Buildings process.", "No estimate effect.", "Narrow the claim to the repealed general permit-notice rule.", "institutional source review")
add("I07", "Medium", "Institution", "citation coverage incomplete", "data.tex:52-67", "Bibliography and cited reporting", "The Fern Hill example and quoted facts are supported by the cited source.", "The episode is broadly verifiable, but the current citation does not support every factual detail and quotation in the paragraph.", "No estimate effect.", "Add direct sources for the unsupported details or trim them.", "citation review")
add("I08", "Medium", "External validity", "unsupported generalization", "discussion.tex:32-35", "Not implemented in code", "The mechanism generalizes to most major U.S. cities.", "The paper establishes a Chicago mechanism and cites related institutions elsewhere, but does not support a claim about most major cities.", "Interpretive only.", "Narrow the external-validity statement.", "line-by-line manuscript review")
add("I09", "Pass", "Institution", "verified", "intro.tex:15-18", "ward_panel_create; create_alderman_data", "Political authority changes at ward boundaries.", "The spatial pipeline uses official ward polygons and assigns distinct ward-alderman regimes on opposite sides of boundaries.", "None.", "Retain.", "segment_rebuild_summary.csv")
add("I10", "Pass", "Institution", "verified externally", "data.tex:140-145", "Not a production-code claim", "HUD characterized aldermanic prerogative as a local veto with fair-housing consequences.", "The quoted characterization and the civil-rights dispute are supported by the reviewed HUD and litigation sources.", "None.", "Retain with the direct sources.", "institutional source review")
add("I11", "High", "Institution", "formal power overstated", "discussion.tex:36-39", "Chicago zoning amendment process", "Aldermen retain unilateral power to downzone parcels preemptively.", "An alderman can initiate and, through council deference, usually obtain a downzoning, but a zoning-map amendment remains a formal legislative action rather than a unilateral legal act.", "No estimate effect; overstates the institutional mechanism.", "Describe proposal plus council deference rather than unilateral formal power.", "institutional source review")
add("I12", "Medium", "Institution", "speculative policy claim", "discussion.tex:39", "Not implemented in code", "Creating a city charter would allow all rules to be codified and thereby limit discretion.", "Chicago can and does codify land-use rules without a charter. Whether a charter would constrain informal discretion depends on its content, not charter status alone.", "Policy interpretation only.", "Frame this as a proposed governance reform rather than a mechanical legal consequence.", "institutional source review")

# Stringency score construction
add("S01", "High", "Score", "sample description mismatch", "data.tex:151-155; appendix_A_data.tex:35-46", "clean_building_permits/code/building_permits_cleaning.R:58-66,89-90", "The permit data include all applications and processing records, excluding missing or negative processing times.", "The downloaded portal extract is an issued-permit file for the relevant records, and production also requires processing_time >= 0. It does not establish coverage of applications never issued.", "Limits interpretation of both the score and event-study outcome.", "Describe the observed file precisely and determine whether a separate application-status source exists.", "permit_event_outcome_portal_coverage.csv")
add("S02", "Pass", "Score", "verified", "data.tex:153-155", "clean_building_permits/code/building_permits_cleaning.R:58-66", "Processing time is issue date minus application date and negative values are excluded.", "The cleaning code implements this definition.", "None.", "Retain, subject to the zero-day issue below.", "permit_processing_time_validation.csv")
add("S03", "Critical", "Score", "undocumented sample exclusion", "data.tex:153-155; appendix_A_data.tex:44-46", "data_for_alderman_uncertainty_index/code/prepare_uncertainty_data.R:342-364", "Nonnegative processing times enter the stringency score.", "Zero-day permits survive cleaning but are converted to missing by log(if_else(processing_time > 0, ...)) and then dropped. Zero-day shares are 38.4% for high-discretion and 73.7% for low-discretion permits.", "Using log(days with zero coded as one) changes the 2022 score correlation to 0.754 and the 2014 correlation to 0.834. The event-study coefficient changes from -0.101 to -0.0577, and the continuous density estimates weaken sharply.", "Choose and defend the score estimand, implement it explicitly, rebuild every score vintage, and update all dependent results before submission.", "permit_zero_day_score_summary.csv; permit_zero_day_score_correlations.csv; permit_zero_day_score_downstream_models.csv")
add("S04", "High", "Score", "label mismatch", "data.tex:160-168; repeated permit definitions", "clean_building_permits/code/building_permits_cleaning.R:69-75", "High-discretion permits are major renovations and other large discretionary projects.", "Production includes every RENOVATION/ALTERATION permit, not a cost- or scope-defined major-renovation subset. This category supplies 144,700 nonnegative-day permits.", "The score is driven heavily by a broader renovation category than the prose suggests.", "Use the exact category label or define and test a defensible major-renovation restriction.", "permit_high_discretion_type_profile.csv")
add("S05", "Pass", "Score", "verified", "data.tex:160-168", "clean_building_permits/code/building_permits_cleaning.R:69-86", "The high-discretion group includes new construction, renovation/alteration, demolition, porch construction, and reinstated permits.", "The production indicator uses exactly these five portal permit types.", "None.", "Define once and refer back to it.", "permit_type_sample_counts.csv")
add("S06", "Pass", "Score", "verified", "appendix_A_data.tex:40-42", "create_event_study_permit_data outcome metadata", "The low-discretion placebo excludes sign permits.", "The event-study outcome n_low_discretion_nosigns excludes signs.", "None.", "Retain.", "permit_type_sample_counts.csv")
add("S07", "Low", "Score", "timing bug with negligible effect", "appendix_A_data.tex:48-50", "data_for_alderman_uncertainty_index/code/prepare_uncertainty_data.R; create_alderman_data", "Permits are assigned using the ward map and alderman in office at application time.", "All May 2015 applications receive the new map, but the alderman panel assigns May to the outgoing incumbent. This changes 105 permit assignments. The 2022 score correlation is 0.99995 and the maximum score change is 0.055.", "Negligible for current estimates, but the implementation is internally inconsistent.", "Use the exact May 18 transition date or a consistent monthly convention.", "score_transition_month_summary.csv")
add("S08", "Pass", "Score", "verified", "appendix_B_alderman_fe.tex:13-18", "data_for_alderman_uncertainty_index; create_alderman_uncertainty_index", "Stage 1 residualizes log processing time using ward covariates, lag volume, month, permit-type, and review-type fixed effects; Stage 2 uses ward-month means and alderman fixed effects.", "The formulas and two-stage sequence match production.", "None.", "Retain after resolving the input sample.", "score_rebuild_summary.csv")
add("S09", "Medium", "Score inference", "inference limitation", "appendix_B_alderman_fe.tex:38-43", "create_alderman_uncertainty_index stage-1 table", "The reported Stage 1 standard errors support the table's stars.", "The table uses IID standard errors despite repeated permits within aldermen, wards, and months.", "The table is descriptive and its stars should not be treated as structural validation.", "Relabel as descriptive or use defensible clustered inference.", "source-code review")
add("S10", "Medium", "Score inference", "inference limitation", "appendix_B_alderman_fe.tex:16-22", "create_alderman_uncertainty_index code", "Stage 2 alderman effects are precisely estimated after aggregation.", "Stage 2 treats 10,101 ward-month observations as heteroskedastic but independent; serial and spatial dependence are not modeled.", "Generated-score uncertainty is understated.", "Report the uncertainty limitation and consider a clustered or bootstrap score construction.", "score_uncertainty_metadata.csv")
add("S11", "Pass", "Score", "verified", "appendix_B_alderman_fe.tex:21-26", "create_alderman_uncertainty_index code", "Empirical Bayes shrinkage and standardization are applied.", "The score is shrunk using the stated formula and standardized across aldermen.", "None.", "Retain.", "score_rebuild_summary.csv")
add("S12", "High", "Generated regressor", "uncertainty omitted", "all score-based models", "downstream regressions", "The estimated score can be treated as measured without error in downstream inference.", "Median propagated score standard errors are 0.398 for the 2014 score and 0.421 for the 2022 score. Many pair orderings are uncertain, while downstream standard errors condition on the point estimates.", "Confidence intervals do not include score-estimation uncertainty. Restricting to confidently ordered pairs generally preserves or strengthens results, but it changes the estimand and sample.", "At minimum disclose generated-regressor uncertainty; preferably add a bootstrap or principled sensitivity analysis.", "score_uncertainty_metadata.csv; score_order_uncertainty_summary.csv; score_confident_pair_model_sensitivity.csv")
add("S13", "Pass", "Score vintage", "verified", "empirics_results.tex:76-86; appendix_A_data.tex:61-68", "run_event_study_permit; create_alderman_uncertainty_index", "The event study uses a score estimated only through 2014.", "The main event-study treatment is explicitly overwritten with the frozen through-2014 score.", "None.", "Retain and encode the vintage clearly in every upstream filename.", "permit_event_score_lineage_summary.csv")
add("S14", "Pass", "Score vintage", "verified", "density, rent, and sales sections", "merge_in_scores; merge_event_study_scores", "Density, rent, and sales use the December 2022 score.", "The current paper-facing datasets use the through-2022 score for these three designs.", "None.", "Retain.", "model reproduction outputs")
add("S15", "Medium", "Score validation", "interpretation too strong", "appendix_B_alderman_fe.tex:59-68", "within_ward_strictness output", "Weak predecessor-successor correlation establishes that the score is not ward-level.", "The exact Pearson correlation is 0.185 and Spearman correlation is 0.153 across 57 pairs. This is consistent with alderman variation but does not isolate it from time-varying ward conditions or noise.", "No direct estimate change.", "Describe this as suggestive diagnostic evidence.", "permit_predecessor_successor_check.csv")
add("S16", "Pass", "Score placebo", "verified", "appendix_B_alderman_fe.tex:72-82", "within_ward_strictness output", "The main score does not predict low-discretion processing time.", "The compact placebo estimate is 0.020 with SE 0.028, N=112.", "None.", "Retain as a descriptive placebo.", "permit_descriptive_group_statistics.csv")
add("S17", "Medium", "Score controls", "bad-control rationale", "appendix_B_alderman_fe.tex:28-31", "Stage 1 formula", "Permit and review type fixed effects are included because their composition may be endogenous to the regulatory environment.", "If aldermen affect permit or review type, conditioning on them could remove part of the mechanism. Endogeneity is not a reason to partial out a variable.", "Interpretation of the score changes depending on whether these are confounders or channels.", "Rewrite the rationale and present a no-type-FE score sensitivity if the score remains central.", "line-by-line model review")
add("S18", "Medium", "Permit descriptives", "causal interpretation unsupported", "data.tex:167-172; appendix_D_permits.tex:87-101", "permit_summary_stats", "Negative high-discretion processing-time/volume correlation reflects political friction, while the positive low-discretion correlation reflects administrative scale.", "The positive-day Pearson correlations reproduce at -0.123 for high-discretion and +0.106 for low-discretion ward-months. These unconditional correlations do not identify either mechanism and change when zero-day permits are included.", "No direct effect on headline regressions, but the descriptive interpretation is too strong.", "Report the correlations without assigning a causal mechanism.", "permit_descriptive_volume_correlations.csv")
add("S19", "Medium", "Score validation", "visual balance overinterpreted", "data.tex:207-212", "strictness_score_map", "Geographic score variation rules out location and local demand as explanations.", "A map showing high and low scores in different parts of Chicago does not rule out correlated local demand, composition, or unmeasured ward conditions.", "Interpretive only.", "Describe the map as showing geographic dispersion, not as ruling out confounding.", "line-by-line manuscript review")
add("S20", "Medium", "Score controls", "volume definition narrower than label", "data.tex:187-205; appendix_B_alderman_fe.tex:13-18", "data_for_alderman_uncertainty_index", "Lagged ward-month permit volume counts the relevant permit flow.", "The lag-volume control is constructed after zero-day permits have been dropped from the score sample, so it measures positive-processing-time high-discretion volume rather than all high-discretion permit volume.", "Could alter residualization where same-day issuance is common.", "Name the control precisely or construct it before the processing-time outcome restriction.", "source-code review")
add("S21", "Medium", "Score sample", "status rule undisclosed", "data.tex:151-180; appendix_A_data.tex:32-50", "clean_building_permits; data_for_alderman_uncertainty_index", "The score uses completed/eligible permit processing records.", "The positive-day score sample includes 416 suspended, 263 cancelled, and 189 revoked high-discretion records, plus 16,535 records with missing status.", "Small share of the score sample, but the inclusion rule is not stated and differs from the event-study status rule.", "Specify a score-sample status rule and show a restricted sensitivity.", "permit_status_profile.csv")

# Density sample, spatial construction, and regressions
add("D01", "Critical", "Density data", "observation-unit bug", "data.tex:223-239; appendix_A_data.tex:87-110", "residential_improvements_data_cleaning/code/residential_improvements_cleaning.R:113-128", "The residential cross-section contains one row per building or PIN-card.", "The comment says one row per (PIN, card), but the code groups only by PIN and selects one card. Downstream tiebacks then create 119 duplicate-key rows in 57 groups. The 500ft production data have 3,660 rows but only 3,598 distinct building keys.", "Joint same-year-card and tieback aggregation changes multifamily continuous FAR from -0.153 to -0.0567 and DUPAC from -0.130 to -0.0330. Only the multifamily binary DUPAC estimate remains conventionally significant in that variant.", "Decide whether the estimand is building-card, parcel-year, or project; rebuild the cross-section at that unit with explicit aggregation rules; then rerun all density results.", "density_building_identity_summary.csv; density_residential_card_models.csv")
add("D02", "High", "Density reporting", "unit label mismatch", "appendix_A_data.tex:101-110; summary table", "summary_stats_new_construction output", "The full sample contains 12,476 buildings.", "12,476 is the number of selected output rows, but only 12,198 distinct (PIN, card) building keys are present.", "Summary labels overstate the unique building count.", "Update the count and label after the observation unit is fixed.", "density_building_identity_summary.csv")
add("D03", "Critical", "Density geocoding", "current-vintage survivorship", "appendix_A_data.tex:96-100", "geocode_ccao_data/code/geocode_residential_data.R:71-88; geocode_ccao_data/code/Makefile", "New-construction parcels are geocoded for the 2006-2022 sample.", "Production requires each historical PIN to exist in the 2025 parcel universe. Of 13,714 eligible PINs, 1,229 lack current coordinates, including 493 of 2,627 multifamily PINs.", "Exact-year historical coordinates add 322 all-construction and 185 multifamily observations within 500ft. Continuous all-construction estimates flip positive; multifamily FAR changes from -0.153 to -0.109 and DUPAC from -0.130 to -0.070.", "Use construction-year historical parcel coordinates with deterministic fallback rules and report coverage.", "density_geocoding_attrition.csv; density_historical_recovery_models.csv")
add("D04", "High", "Density construction year", "ambiguous source selection", "appendix_A_data.tex:89-99", "residential_improvements_data_cleaning/code/residential_improvements_cleaning.R:113-121", "Assessor year built identifies construction year.", "The code selects the minimum reported year across a PIN's tax history. Reported year is revised for 7,049 PIN-cards; 689 move into the 2006-2022 window under the latest report and 4 move out.", "Parcel-year latest-report multifamily continuous estimates are -0.0049 for FAR and +0.0446 for DUPAC, while card-level latest-report estimates remain negative. This reinforces that year rule and observation unit must be resolved jointly.", "Define a defensible construction-year rule, inspect bunching, and rerun at the chosen unit.", "density_year_built_revision_summary.csv; density_year_built_revision_models.csv; density_year_built_counts.csv")
add("D05", "Pass", "Density timing", "verified", "appendix_A_data.tex:96-100", "calculate_ward_boundary_distances/code/calculate_distances.R", "June 15 is imputed when only construction year is observed.", "Production uses June 15 and assigns the ward map and alderman in effect on that date.", "Timing audits show limited sensitivity relative to the larger sample-construction issues.", "Retain with the existing disclosure if the density sample survives rebuilding.", "density treatment timing audit")
add("D06", "Pass", "Density spatial join", "verified", "appendix_A_data.tex:96-100", "calculate_ward_boundary_distances; border_segment_creation; assign_segment_ids", "Parcels use centroids, EPSG:3435, and nearest ward boundaries.", "The audited spatial steps use 4326 for raw points and 3435 for Chicago geometry, assign by centroid, and compute distances in State Plane feet.", "None detected.", "Retain.", "segment_rebuild_summary.csv")
add("D07", "Pass", "Density segmentation", "exact rebuild", "empirics_results.tex:6-66", "border_segment_creation; assign_segment_ids", "Boundary segments and parcel assignments are deterministic.", "A fresh audit rebuild reproduced all 4,777 segment classifications and all 27,054 parcel segment assignments exactly.", "None.", "Retain.", "segment_rebuild_summary.csv")
add("D08", "Critical", "Density zoning", "stale output and changed sample", "intro.tex:27; empirics_results.tex:10-66", "zoning_data_cleaning/code/clean_zoning_data.R:89-110; cached zoning_data_clean.gpkg", "The paper's zoning-controlled density sample reflects the active production source.", "The active script removes PD, PMD, and POS polygons, but the cached paper-facing output still includes them. A fresh rebuild drops 648 of 3,660 all-construction rows and 122 of 701 multifamily rows.", "Fresh multifamily continuous FAR changes from -0.153 (p=.019) to -0.0447 (p=.442), and DUPAC from -0.130 (p=.018) to -0.0638 (p=.253). Binary multifamily estimates remain negative and significant.", "Resolve the intended PD/PMD/POS treatment, rebuild zoning and every descendant, and do not submit cached estimates from code that no longer produces them.", "density_zoning_summary.csv; density_model_reproduction.csv")
add("D09", "High", "Density zoning", "vintage mismatch", "intro.tex:17,27; empirics_results.tex:10-66", "zoning_data_cleaning/code/Makefile", "The design compares parcels with similar statutory zoning at construction.", "The zoning control is based on a September 2025 zoning map, not the zoning in effect when projects were built from 2006-2022.", "Current zoning can be post-treatment and may differ because of the same development process being studied.", "Reconstruct historical zoning or explicitly redefine and qualify the control.", "task lineage and zoning source review")
add("D10", "Pass", "Density model", "verified", "empirics_results.tex:6-53", "border_pair_FE_regressions", "The 500ft model uses own-side controls, side-specific distance slopes, zoning-group, segment, and year fixed effects, with ward-pair clustered standard errors.", "The production formula matches the manuscript and the table estimates reproduce exactly on the cached input.", "None conditional on the input data being correct.", "Retain after rebuilding the sample.", "density_model_reproduction.csv")
add("D11", "Pass", "Density estimates", "exact reproduction", "paper.tex:54; intro.tex:29-30; empirics_results.tex", "border_pair_FE_regressions output", "Published continuous and binary density coefficients match production.", "Cached-input estimates reproduce exactly, including continuous multifamily FAR -0.153 and DUPAC -0.130 and binary multifamily FAR -0.267 and DUPAC -0.359.", "None conditional on unresolved density inputs.", "Update only after rebuilding the sample.", "density_model_reproduction.csv")
add("D12", "High", "Density figure", "visual/model mismatch", "empirics_results.tex:54-66", "nonparametric_rd_density_linear_display/code/nonparametric_rd_density_linear_display_combined.R:126-177", "Figure fitted lines depict the same model reported in the subtitles and table.", "The script residualizes only the outcome and then fits side by raw distance. It does not residualize the treatment and distance regressors as exact FWL requires. The subtitle comes from the full model, while the plotted line comes from a different regression.", "Plotted jumps are much smaller: multifamily FAR -0.077 versus reported -0.267 and DUPAC -0.100 versus -0.359.", "Construct adjusted values or fitted lines from the exact reported model and regenerate all density display, placebo, and donut figures.", "density_display_spec_comparison.csv")
add("D13", "Medium", "Density source", "sample label mismatch", "data.tex:225-228", "geocode_ccao_data/code/geocode_residential_data.R", "Residential assessor data cover up to six units and commercial data cover larger buildings.", "Production source-priority logic selects the commercial row for some overlapping PINs regardless of size; 23 commercial-selected 500ft rows have six or fewer units.", "Small direct consequence, but the source rule differs from the prose.", "State the actual source-priority rule and retain a source-sensitivity table in the audit.", "density_commercial_source_summary.csv")
add("D14", "Medium", "Density source", "manual interventions", "data.tex:223-239", "commercial_value_data_cleaning", "The density sample is mechanically constructed from assessor sources.", "The 500ft commercial component contains one manual unit override, two land-area corrections, and 132 multi-PIN buildings. These are limited but should be documented.", "Small estimated effect in the audit.", "Document the interventions and their provenance in the appendix or replication README.", "density_commercial_source_summary.csv; density_commercial_source_models.csv")
add("D15", "Medium", "Density controls", "post-treatment risk", "empirics_results.tex:10-53", "create_ward_controls; border_pair_FE_regressions", "Annual own-ward demographic controls improve comparability.", "Own-side annual demographics can respond to development and are therefore potentially post-treatment. Alternate demographic-control vintages do not drive the cached multifamily result.", "Limited empirical consequence in tested variants, but causal interpretation should not rely on these controls.", "Prefer predetermined controls or show the no-demographic specification.", "density_demographic_control_sensitivity.csv")
add("D16", "Medium", "Density sample", "available pruning not used", "empirics_results.tex:6-66", "border_confound_pruning outputs; border_pair_FE_regressions", "The main sample is restricted to clean boundary comparisons.", "Production does not apply the available confounded-segment or confounded-pair flags in the main density model.", "Potentially affects design credibility; not identified as the source of current headline sensitivity.", "Decide ex ante whether these flags define the design sample and report the choice.", "task source review")
add("D17", "Pass", "Density summary statistics", "exact cached reproduction", "appendix_A_data.tex:101-110", "summary_stats_new_construction", "Means, medians, and cached row counts match the generated table.", "The reported statistics match the current cached dataset, apart from the 'building' unit label.", "None conditional on sample rebuild.", "Regenerate after fixing D01-D04 and D08.", "isolated_rebuild_artifact_comparison.csv")
add("D18", "Medium", "Density inference", "cluster sensitivity", "empirics_results.tex:10-66", "border_pair_FE_regressions", "Ward-pair clustering captures dependence at political boundaries.", "Ward pairs share wards, so pair clusters are not independent. Endpoint-based two-way clustering raises the multifamily continuous FAR SE from 0.0640 to 0.0917 (p=.102); DUPAC remains p=.029.", "One of two continuous multifamily outcomes loses conventional significance.", "Present a defensible shared-ward clustering sensitivity and avoid treating pair-cluster inference as uniquely correct.", "inference_cluster_sensitivity.csv")
add("D19", "Pass", "Density placebo", "cached estimates verified", "appendix_C_density.tex:10-75", "nonparametric_rd_density_placebo", "Shifted cutoffs do not reproduce the main boundary jump.", "All eight cached placebo subtitles are statistically insignificant. All-construction jumps range from -0.024 to 0.026; multifamily jumps range from -0.126 to 0.193 with large standard errors.", "Supports cutoff specificity on the cached sample, but the plotted lines inherit D12's residualization mismatch and the sample inherits the density blockers.", "Regenerate after fixing the density data and exact display model.", "extracted placebo PDF text")
add("D20", "Pass", "Density donut", "cached estimates verified", "appendix_C_density.tex:77-142", "nonparametric_rd_density_donut", "The density discontinuity remains negative after excluding observations within 25ft or 50ft.", "All eight cached donut subtitle estimates are negative. Multifamily binary FAR is -0.267/-0.294 and DUPAC is -0.359/-0.387 for 25ft/50ft donuts.", "Supports that immediate-boundary parcels do not drive the cached result, but figures inherit D12 and all density sample blockers.", "Regenerate after the density sample is fixed.", "extracted donut PDF text")

# Permit event study
add("E01", "Pass", "Permit event study", "verified", "appendix_A_data.tex:54-68", "create_block_treatment_panel", "Blocks are assigned to pre/post wards by largest-area overlap in EPSG:3435.", "The treatment panel uses largest-area polygon overlap after projection.", "None.", "Retain.", "permit_spatial_design_summary.csv")
add("E02", "Pass", "Permit event study", "verified", "appendix_A_data.tex:61-75", "merge_event_study_scores; run_event_study_permit", "Treatment is the destination-minus-origin score difference using 2014 incumbents and through-2014 scores.", "The production main specification implements exactly this predetermined assigned-change ITT.", "None.", "Retain.", "permit_event_score_lineage_summary.csv")
add("E03", "Pass", "Permit event study", "verified", "empirics_results.tex:68-118", "run_event_study_permit", "The model uses block fixed effects, ward-pair by year fixed effects, and pre-period volume and zero-volume controls interacted with year.", "The production PPML formula matches the paper.", "None.", "Retain.", "permit_event_model_reproduction.csv")
add("E04", "Pass", "Permit event study", "verified", "appendix_A_data.tex:77-82", "create_event_study_permit_data; run_event_study_permit", "The analysis spans 2010-2020 and applies a 500ft local-support restriction using census-block centroids.", "The main sample uses centroid distance <=152.4 meters to the specified pre-redistricting boundary geometry.", "None.", "Retain and keep the centroid language explicit.", "permit_spatial_design_summary.csv")
add("E05", "Critical", "Permit outcome", "central interpretation mismatch", "paper.tex:55; intro.tex:32-35; empirics_results.tex:76-102; discussion.tex:16-24; conclusion.tex:11", "clean_building_permits; create_event_study_permit_data/code/create_permit_block_year_panel.R:257-285,424-435", "The outcome is the flow of applications entering permitting and therefore measures deterrence on the application margin.", "The event panel counts records in the issued-permit extract by application year. Every relevant 500ft record has an issue year; applications that never reach this file are unobserved. The design identifies changes in observed issued-file permits indexed by filing year, not all submitted applications or projects deterred before issuance.", "The -0.101 coefficient reproduces, but the extensive-margin/deterrence interpretation is not established by these data.", "Either obtain a true application universe with unresolved/denied applications or rewrite the estimand throughout as observed permits by application date.", "permit_event_outcome_portal_coverage.csv; permit_event_date_status_sensitivity.csv")
add("E06", "High", "Permit outcome", "status description mismatch", "appendix_A_data.tex:40-42", "create_event_study_permit_data/code/create_permit_block_year_panel.R:257-266", "Event outcomes include issued or expired applications and exclude cancelled, revoked, or suspended applications.", "The query excludes cancelled/revoked/suspended but also includes records with missing status. In the 500ft design blocks there are 29,650 missing-status records, 49,370 issued-status records, and 565 expired records.", "The main high-discretion coefficient is stable to status variants, but the paper's outcome definition is incomplete.", "Describe all included statuses and explain why missing status is retained.", "permit_event_outcome_portal_coverage.csv; permit_event_date_status_sensitivity.csv")
add("E07", "High", "Permit event sample", "text/code mismatch", "appendix_A_data.tex:70-75", "create_block_treatment_panel/code/create_treatment_panel.R:196-223", "Blocks are retained regardless of electoral turnover.", "Treated switchers are retained, but unchanged controls are excluded when their origin ward had 2015 turnover. This removes 10,267 blocks before the local-support restriction.", "A turnover-agnostic reconstruction changes the high-discretion estimate only from -0.10102 to -0.10114, so the mismatch is not driving the result.", "Either remove the control exclusion or describe the actual sample rule and justify it.", "permit_event_treatment_sample_rules.csv; permit_event_model_reproduction.csv")
add("E08", "Medium", "Permit timing", "partial-treatment year", "empirics_results.tex:68-118; appendix_D_permits.tex", "run_event_study_permit", "Year 0 is the first post-remap year.", "The 2015 map began May 18, but annual aggregation treats all of 2015 as post. Ward-pair by year fixed effects absorb common levels, not within-year treatment timing.", "This attenuates or mixes the year-0 coefficient; pooled results include the partially treated year.", "Disclose the annual convention and retain the transition-year sensitivity in the audit or appendix if needed.", "corrected_permit_event_study transition-year audit")
add("E09", "Pass", "Permit event estimate", "exact reproduction", "paper.tex:55; empirics_results.tex:100-118", "run_event_study_permit", "The main assigned-stringency coefficient is -0.101 with SE 0.032, implying a 9.6% lower annual flow.", "Exact reproduction: -0.101024, SE 0.032000, p=.00159, 60,898 PPML observations, 5,559 blocks, and 105 ward pairs after PPML dropping.", "None conditional on E05's outcome interpretation and S03's score definition.", "Retain numerical values only after those decisions.", "permit_event_model_reproduction.csv")
add("E10", "Pass", "Permit placebo", "exact reproduction", "appendix_D_permits.tex:15-47", "run_event_study_permit", "Low-discretion coefficient is -0.063 with SE 0.038 and p=.100.", "Exact reproduction: -0.062900, SE 0.038195, p=.0996.", "None.", "Retain as a placebo estimate.", "permit_event_model_reproduction.csv")
add("E11", "Medium", "Permit placebo", "difference not significant", "appendix_D_permits.tex:17-18,35-45", "joint coefficient test audit", "Low-discretion applications show a meaningfully more muted response.", "The main ITT high-minus-low difference is -0.0381 with SE 0.0427 and p=.372. The point estimate is smaller, but the two effects are not statistically distinguishable.", "Weakens claims that the main ITT response is specific to high-discretion permits.", "Call the low-discretion response descriptively smaller and report the difference test.", "corrected_permit_event_study test_itt_discretion_difference.R")
add("E12", "Pass", "Permit robustness", "exact reproduction", "appendix_D_permits.tex:49-66", "run_event_study_permit", "Stable-incumbent coefficient is -0.142 with SE 0.041, or 13.2% lower.", "Exact reproduction: -0.141798, SE 0.040825, p=.000514.", "None conditional on selection into incumbent stability.", "Retain as a robustness check, not the main design.", "permit_event_model_reproduction.csv")
add("E13", "Pass", "Permit spatial robustness", "robust", "appendix_A_data.tex:80-81", "audit point-on-surface reassignment", "Centroid-based 500ft assignment is not driving the estimate.", "Point-on-surface reconstruction changes 277 block assignments and yields -0.0902 (SE .0335) versus -0.1010 (SE .0320).", "Main conclusion is stable.", "No production change required unless point-on-surface better matches the intended design.", "permit_surface_point_model_sensitivity.csv")
add("E14", "Pass", "Permit PPML", "verified", "appendix_D_permits.tex:27-32", "run_event_study_permit", "Fixed-effect PPML drops all-zero blocks and all-zero ward-pair-year groups.", "The notes accurately describe fixest's outcome-based fixed-effect dropping. The design balance table therefore need not have the same pair count as the PPML estimation sample.", "None.", "Retain the current disclosure.", "permit_event_model_reproduction.csv")
add("E15", "Pass", "Permit balance", "correctly disclosed", "appendix_D_permits.tex:8-13", "permit_itt_balance", "The balance table describes the design sample rather than the exact PPML estimation sample.", "The table uses 82 pairs with both treated and unchanged blocks; PPML retains 105 pairs after outcome-specific dropping. Current table notes distinguish these samples.", "None.", "Retain.", "permit_balance_geography_summary.csv")
add("E16", "Medium", "Permit clustering", "dependence concern", "empirics_results.tex; appendix_D_permits.tex", "run_event_study_permit", "Ward-pair clusters are independent sampling units.", "Different ward pairs can share a ward. Pair clustering does not account for dependence induced by a common alderman or ward endpoint.", "Alternative clustering changes precision in some specifications; the main estimate remains negative in tested variants.", "Present a shared-ward or multiway sensitivity and explain the chosen cluster level.", "inference_cluster_sensitivity.csv")
add("E17", "Pass", "Permit balance", "robust inference", "appendix_D_permits.tex:8-13", "permit_itt_balance", "Predetermined outcomes and block-group characteristics are broadly balanced.", "Published pair-cluster, block-group-cluster, two-way, and cell-aggregation checks are broadly similar. Median age is the notable row with a pair-cluster p-value near .012, but not under equal-weight cell aggregation.", "No broad balance failure.", "Report the table as descriptive and avoid highlighting individual stars.", "permit_balance_inference_sensitivity.csv")
add("E18", "Pass", "Permit spatial join", "exact independent reconstruction", "appendix_A_data.tex:48-60,77-81", "create_block_treatment_panel; create_event_study_permit_data", "Permit points, census blocks, event boundaries, and ward pairs are joined consistently.", "An independent reconstruction produced exactly the same 8,273 500ft blocks, event-pair IDs, and distances as production. Four centroid-majority disagreements are excluded by the current agreement rule.", "No spatial-join discrepancy found in the final 500ft permit panel.", "Retain.", "permit_spatial_panel_comparison.csv; permit_spatial_design_summary.csv")

# Rental pipeline
add("R01", "Pass", "Rental data", "verified", "data.tex:241-249; appendix_A_data.tex:134-154", "process_rent_data", "RentHub rows are collapsed to floorplan-day medians and then floorplan-month medians using transparent proxy identifiers.", "The production cleaning implements the described address/property/floorplan proxies and median collapses.", "None.", "Retain.", "rental_key_source_summary.csv; rental_unit_id_collision_summary.csv")
add("R02", "High", "Rental geography", "pre-spatial city filter attrition", "appendix_A_data.tex:16-18,149", "process_rent_data city filter", "Illinois listings are restricted to Chicago using ward assignment.", "Production first accepts only city labels CHICAGO or CHGO. At least 15,585 raw rows in 1,629 coordinate cells physically inside Chicago have other city labels and are excluded before ward assignment.", "The tested CHGO sensitivities barely change the estimate, but the unaccepted in-city labels are not present in the production panel and cannot be fully re-estimated without rebuilding.", "Use spatial inclusion as the Chicago restriction or document and audit the label filter comprehensively.", "rental_city_raw_spatial_summary.csv")
add("R03", "Medium", "Rental cleaning", "undisclosed trimming", "data.tex:241-249; appendix_A_data.tex:137-154", "process_rent_data", "The appendix fully describes rental cleaning.", "Production trims rent and square footage within year-by-bedroom groups at the 1st and 99th percentiles. It drops 96,848 rent-days and 57,278 square-foot-days, but this is not disclosed.", "Potential sample-selection issue; current main estimate not separately identified as sensitive to it.", "Disclose the trimming rule and add an untrimmed/wider-trim sensitivity.", "rental_trimming_summary.csv")
add("R04", "Pass", "Rental sample", "verified", "appendix_A_data.tex:149-154", "rental_rd", "The main model uses the clean-location sample and retains studios.", "The model requires the clean-location flag and includes 28,526 studio observations using categorical bedrooms.", "None.", "Retain.", "rental_sample_attrition.csv; rental_model_reproduction.csv")
add("R05", "High", "Rental attrition", "large complete-case loss", "appendix_A_data.tex:153-154", "rental_rd", "The regression requires square footage, bathrooms, and amenity controls.", "After the 500ft and clean-location restrictions, 147,661 of 387,976 observations are dropped for missing or nonpositive square footage or bathrooms. The final N is 240,315.", "The main result is conditional on a selected listing subset.", "Report an attrition table and compare a parsimonious specification that does not require square footage.", "rental_sample_attrition.csv")
add("R06", "Medium", "Rental location QC", "incomplete validation", "appendix_A_data.tex:149-152", "renthub_quality_flags", "All clean locations receive modal-coordinate stability checks.", "12,201 regression observations lack an address and therefore cannot receive address-modal coordinate checks, although generic-coordinate filters still apply.", "Limited known consequence; should be disclosed as a limit of the clean-location flag.", "Clarify which checks apply only to address-bearing listings.", "rental_unchecked_location_summary.csv")
add("R07", "Pass", "Rental model", "exact reproduction", "paper.tex:56; intro.tex:39; empirics_results.tex:120-167", "rental_rd", "Listed rents are about 3.5% higher on the stringent side in the flat 500ft model.", "Exact coefficient 0.034270, SE 0.007745, p<.001, N=240,315, corresponding to 3.49%.", "None conditional on R02-R06.", "Retain numerical value after final sample decision.", "rental_model_reproduction.csv")
add("R08", "Pass", "Rental model", "verified", "empirics_results.tex:120-167", "rental_rd", "The model includes segment-by-month fixed effects, hedonic controls, amenity controls, and segment-clustered errors.", "The production formula matches the notes and the display uses the exact fitted-model adjustment.", "None.", "Retain.", "rental_model_reproduction.csv")
add("R09", "Medium", "Rental support", "limited two-sided cells", "empirics_results.tex:120-167", "rental_rd", "The segment-by-month design compares both sides within most fixed-effect cells.", "Only 11,974 of 38,016 segment-month cells are two-sided; the rest contribute to controls and fixed effects but not direct within-cell side comparisons.", "Does not invalidate the estimator, but clarifies where identification comes from.", "Report support diagnostics or restrict as a sensitivity.", "rental_model_reproduction.csv")
add("R10", "Pass", "Rental timing", "verified", "data.tex:241-249", "calculate_rent_distances", "Ward maps and aldermen follow the exact May 18, 2015 transition.", "The monthly/listing-date assignment is internally consistent with the stated map transition.", "None.", "Retain.", "rental_transition_month_summary.csv")

# Sales pipeline
add("H01", "Pass", "Sales sample", "verified", "appendix_A_data.tex:115-121", "calculate_sale_distances/code/calculate_sale_distances.R:45-52", "The class, price, deed, land-sale, and single-parcel restrictions are implemented.", "Production uses the stated residential classes, price > $10,000, Warranty/Trustee deeds, excludes land, and requires one parcel.", "None.", "Retain.", "sales_class_counts.csv; sales_restriction_validation.csv")
add("H02", "High", "Sales sample", "arm's-length rule overstated", "appendix_A_data.tex:117-119", "calculate_sale_distances/code/calculate_sale_distances.R:45-52", "Valid buyer and seller names are required and intrafamily transfers are excluded.", "Production validates only seller names and removes only exact seller==buyer. It does not identify family relationships. The final model previously contained 279 invalid-buyer rows and 98 repeated-sale flags under stricter diagnostics.", "A stricter audit estimate is 0.0159 (SE .0077), so the headline is robust, but the prose is inaccurate.", "Implement symmetric buyer/seller validity rules and use a precise arm's-length definition, or narrow the claim.", "sales_arm_length_sensitivity.csv")
add("H03", "Medium", "Sales trimming", "analysis-universe mismatch", "appendix_A_data.tex:120-121", "calculate_sale_distances", "Prices are winsorized for the 2006-2022 analysis sample.", "Winsor thresholds are computed over the broader live 1999-2025 cleaned universe before the paper window is imposed.", "The estimate is stable in the audit, but the described population is ambiguous.", "Compute thresholds on the declared analysis universe or state the broader universe.", "sales_price_robustness.csv")
add("H04", "Pass", "Sales geocoding", "verified", "appendix_A_data.tex:123-125", "calculate_sale_distances; prep_sales_border_data", "Full PINs use 2025 coordinates with exact-sale-year historical fallback.", "49,806 of 51,476 model rows use current coordinates and 1,670 use exact-year fallback, matching the stated priority.", "None.", "Retain, while noting that current coordinates dominate historical sales.", "sales_coordinate_source_summary.csv")
add("H05", "Pass", "Sales geocoding", "robust", "appendix_A_data.tex:123-132", "historical-coordinate audit", "Current-coordinate use does not materially drive the price estimate.", "An exact-year historical-coordinate sensitivity produces a similar estimate.", "No material consequence found.", "Retain the sensitivity in audit records.", "sales_historical_coordinate_model_sensitivity.csv")
add("H06", "Pass", "Sales timing", "verified", "appendix_A_data.tex:127-132", "calculate_sale_distances", "Sales use the exact sale date and May 18, 2015 map transition in EPSG:3435.", "The production assignment matches the stated rule and the exact-date sensitivity is stable.", "None.", "Retain.", "sales_may2015_timing_sensitivity.csv")
add("H07", "Pass", "Sales assessor join", "verified after production fix", "appendix_A_data.tex:115-132", "prep_sales_border_data", "Assessor characteristics are matched within sale year.", "All 51,476 model rows have same-year assessor matches. The previously mislabeled hedonic tax year has been corrected in production.", "None.", "Retain.", "sales_model_reproduction.csv")
add("H08", "Medium", "Sales hedonics", "multi-card aggregation ambiguity", "empirics_results.tex:120-167", "prep_sales_border_data", "Building square footage and hedonics represent the full property.", "For 899 multi-card PIN-years, production selects the largest card rather than summing cards; 929 model rows have selected square footage below the card total. The median total/selected ratio is 1.48.", "Summing cards changes the coefficient only from 0.01653 to 0.01622.", "Document the largest-card rule or aggregate cards to the property unit.", "sales_assessor_card_summary.csv; sales_assessor_card_sensitivity.csv")
add("H09", "Pass", "Sales model", "exact reproduction", "paper.tex:56; intro.tex:40; empirics_results.tex:120-167", "sales_border_pair_fe", "Sale prices are about 1.7% higher on the stringent side.", "Exact coefficient 0.016533, SE 0.007670, p=.0312, N=51,476, corresponding to 1.67%.", "None conditional on inference sensitivity.", "Retain numerical value after final inference decision.", "sales_model_reproduction.csv")
add("H10", "Pass", "Sales controls", "verified", "empirics_results.tex:120-167", "sales_border_pair_fe", "Sales and rents use the same coordinate-based amenity families where available.", "Sales include school, park, major-road, CTA, and lake distances along with hedonic controls and segment-by-quarter fixed effects.", "None, subject to amenity-vintage caveats.", "Retain.", "sales_control_missingness.csv")
add("H11", "Medium", "Sales inference", "cluster sensitivity", "empirics_results.tex:120-167", "sales_border_pair_fe", "Segment clustering is sufficient for the boundary comparison.", "Endpoint-based two-way ward clustering raises the SE from .00767 to .01069 and the p-value from .031 to .128.", "The home-price result is not conventionally significant under this dependence correction.", "Present this inference sensitivity and keep the price result explicitly suggestive.", "inference_cluster_sensitivity.csv")
add("H12", "Low", "Price placebo figures", "note/layout mismatch", "appendix_E_price_rd.tex:6-31", "price_rd_stress_tests/code/build_price_rd_main_style_plots.R:36,276-283", "The left and right panels are the two placebo cutoffs.", "Each output has three facets: -1000ft placebo, true boundary, and +1000ft placebo. The notes describe only left and right placebo panels.", "No estimate effect.", "Update the notes to describe all three panels.", "isolated_rebuild_artifact_comparison.csv")

# Amenity vintages
add("A01", "High", "Amenities", "active-date claim overstated", "appendix_A_data.tex:25-27", "prepare_amenities_data/code/prepare_amenities_data.R:6-38", "CTA distances use stations active in each listing or sale month.", "Only five current stations have explicit opening dates. All other current stations are assigned 1900-01-01 and no station has a closing date, so historical closures and most openings are not represented.", "Potential measurement error in rent and sales controls; likely limited for a local design but not audited away.", "Build a complete station opening/closing history or narrow the wording to the implemented approximation.", "source-code review")
add("A02", "Medium", "Amenities", "static vintage", "appendix_A_data.tex:25-27", "prepare_amenities_data/code/prepare_amenities_data.R:41-75", "Amenity controls represent contemporaneous nearby amenities.", "Schools use SY2014-15 locations, while parks and major streets use current files for all years.", "Potential time-varying measurement error.", "State the vintages and treat the controls as mostly time-invariant location characteristics.", "source-code review")
add("A03", "Pass", "Amenities", "verified", "appendix_A_data.tex:25-27", "prepare_amenities_data", "Amenity geometries are projected to EPSG:3435 before distance calculations.", "All audited amenity layers are transformed to EPSG:3435.", "None.", "Retain.", "source-code review")

# Make lineage and reproducibility
add("M01", "Pass", "Reproducibility", "exact immediate rebuild", "short_paper/Makefile", "37 paper-facing task outputs", "Current paper-facing artifacts reproduce from their cached inputs.", "All 37 immediate artifacts regenerated identically or with identical extracted PDF text.", "None at the immediate-producer level.", "Retain audit comparison.", "isolated_rebuild_artifact_comparison.csv")
add("M02", "Pass", "Reproducibility", "clean paper build passes", "short_paper/Makefile", "temporary clean paper directory", "The short paper compiles when paper intermediates and the PDF are absent.", "A clean paper-directory build completed successfully and produced a 59-page PDF.", "None.", "No change required for compilation itself.", "clean build executed 2026-07-16")
add("M03", "High", "Reproducibility", "recursive freshness gap", "short_paper/Makefile; tasks/generic.make:30-48", "generic recursive upstream rule", "A paper make checks every upstream producer even when intermediate outputs already exist.", "GNU Make does not run the prerequisite-free generic pattern recipe for an existing output. Immediate paper producers can therefore see existing task-local symlinks as current while deeper tasks independently request rebuilds.", "Future source or raw-input changes can leave paper-facing outputs silently stale.", "Give upstream output targets real recursive prerequisites or use an explicit force/check mechanism that preserves incrementality throughout the graph.", "lineage_target_dry_run_status.csv")
add("M04", "Low", "Reproducibility", "repository-standard mismatch", "short_paper/Makefile:42-55", "AGENTS.md", "Paper compilation follows the repository convention.", "The current Makefile invokes latexmk directly although project instructions require make-driven pdflatex/bibtex sequencing. It works, so this is a style/maintenance issue rather than a current build failure.", "No analytical effect.", "Align with the project convention when the Make lineage is repaired.", "source review")
add("M05", "Medium", "Reproducibility", "secondary-output risk", "multiple task Makefiles", "test -s secondary output recipes", "All multi-output scripts are represented safely under GNU Make 3.81.", "Several tasks declare one canonical producer and use test -s for secondary outputs. If a secondary file is stale but nonempty, Make cannot verify that it corresponds to the canonical run.", "Can preserve stale side outputs in edge cases.", "Use one canonical target plus explicit secondary dependencies whose freshness is tied to the canonical output.", "task Makefile review")

# Cross-paper interpretation and equations
add("P01", "Pass", "Conceptual model", "algebra verified", "model.tex:11-35", "Not code-dependent", "The developer problem, first-order condition, profit, and participation threshold are algebraically correct.", "The derivations are internally consistent.", "None.", "Retain.", "manual algebra check")
add("P02", "Medium", "Conceptual interpretation", "causal wording too strong", "model.tex:54-57; appendix_B_alderman_fe.tex:19,31", "score construction", "The score measures delay each alderman imposes and isolates the alderman-specific component.", "The score is an alderman fixed effect from observational processing times. Residualization removes listed observables but does not prove causation or isolate alderman effects from time-varying ward factors.", "Affects interpretation, not coefficients.", "Use 'associated with' or 'proxy for' unless a separate design identifies the score itself.", "score and manuscript review")
add("P03", "Critical", "Main thesis", "interpretation exceeds outcome", "intro.tex:34-35; discussion.tex:8-24; conclusion.tex:11", "permit event outcome lineage", "The event study demonstrates deterrence and fewer projects entering permitting.", "Because the outcome is observed issued-file permits indexed by application year, the design does not observe never-issued applications or pre-application deterrence.", "One of the paper's two claimed supply margins is currently overstated.", "Resolve E05 before revising the abstract, introduction, discussion, and conclusion.", "permit_event_outcome_portal_coverage.csv")
add("P04", "High", "Causal claims", "premature causal conclusion", "conclusion.tex:13", "density and permit audits", "The supply-side designs provide causal evidence that informal discretion affects housing production.", "The designs are potentially causal, but the density result is presently sensitive to unresolved observation-unit, geocoding, zoning, and score choices, and the permit outcome has a narrower estimand than claimed.", "Central conclusion is not yet supported at submission standard.", "Defer causal language until D01-D04, D08, S03, and E05 are resolved.", "full audit synthesis")
add("P05", "Pass", "Price interpretation", "appropriately cautious", "model.tex:44-46; paper.tex:56; discussion.tex", "rent and sales models", "Rent and sales results are suggestive downstream evidence rather than the main identification pillar.", "This wording appropriately reflects the designs and sales clustering sensitivity.", "None.", "Retain.", "full audit synthesis")
add("P06", "Pass", "Headline arithmetic", "verified", "abstract, intro, results, conclusion", "generated tables and model outputs", "Reported percentage effects correspond to coefficient transformations.", "All current headline transformations match exp(beta)-1 or the stated log-point approximation, including 9.6%, 13.2%, 3.5%, and 1.7%.", "None conditional on upstream sample decisions.", "Regenerate after analytical fixes.", "model reproduction CSVs")
add("P07", "Pass", "Table 2", "verified", "empirics_results.tex: density table", "border_pair_FE_regressions output", "Table 2 contains continuous and binary density estimates with correct labels, SEs, and sample sizes.", "The generated table matches the cached production regressions.", "None conditional on density rebuild.", "Regenerate after D01-D04 and D08.", "isolated_rebuild_artifact_comparison.csv")
add("P08", "Medium", "Discussion", "mechanism stronger than evidence", "discussion.tex:8-24", "density and permit designs", "Uncertainty and inconsistency make development slower and less predictable and deter projects.", "The score directly uses observed processing time, but the designs do not separately identify uncertainty, delay, redesign, and political bargaining as mechanisms. The event outcome does not observe all deterred projects.", "Mechanism interpretation is suggestive rather than directly tested.", "Separate measured facts from proposed mechanisms.", "full audit synthesis")
add("P09", "Pass", "Bibliography", "verified", "all manuscript citations", "short_paper/sections/aldermanic_privilege.bib", "Every citation key used by the manuscript resolves.", "All 43 cited keys are present. The bibliography also contains 63 unused entries, which do not affect compilation.", "None.", "Optionally prune unused entries after substantive work is complete.", "bibliography key audit")


OUTPUT.mkdir(parents=True, exist_ok=True)
with LEDGER.open("w", newline="") as handle:
    writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
    writer.writeheader()
    writer.writerows(rows)


branch = subprocess.run(
    ["git", "branch", "--show-current"],
    check=True,
    capture_output=True,
    text=True,
).stdout.strip()
counts = Counter(row["severity"] for row in rows)

report = f"""# Short Paper Manuscript-to-Code Audit

**Audit date:** 2026-07-16
**Branch inspected:** `{branch}`
**Scope:** `short_paper/paper.tex`, every included main-text and appendix section, every paper-facing generated artifact, and the upstream cleaning, spatial, score, and estimation tasks.
**Edits made:** None to the manuscript or production code. All new files are confined to `tasks/audits/paper_code_alignment_audit/`.

## Bottom line

The cached paper numbers reproduce, the short paper compiles from a clean paper directory, and many important implementation details are correct. The paper is **not yet ready for submission**, however, because five unresolved issues either materially change headline density estimates or change the interpretation of a central result:

1. The density pipeline says it constructs one row per building `(PIN, card)` but groups by PIN and later contains duplicate building keys. Reasonable parcel/project aggregation sharply attenuates the continuous multifamily estimates.
2. Historical construction is geocoded through the 2025 parcel universe. Missing current PINs disproportionately remove multifamily construction, and recovering exact-year historical coordinates materially changes the estimates.
3. The cached zoning-controlled density result cannot be regenerated by the active zoning source, which now excludes PD/PMD/POS polygons. A fresh rebuild removes about 17% of the 500ft density sample and eliminates the continuous multifamily significance.
4. The score silently drops all zero-day permits even though the paper says nonnegative processing times are used. Zero-day permits are common, and alternate explicit handling materially changes score rankings and downstream results.
5. The permit event study counts permits in the issued-permit extract by application year. It therefore does not observe applications that never reach issuance and cannot, as currently written, establish deterrence or whether projects enter permitting.

These are not cosmetic discrepancies. They should be resolved before line editing or journal submission.

## Severity counts

| Severity | Claims/checks |
|---|---:|
| Critical | {counts['Critical']} |
| High | {counts['High']} |
| Medium | {counts['Medium']} |
| Low | {counts['Low']} |
| Pass | {counts['Pass']} |
| **Total** | **{len(rows)}** |

The accompanying `manuscript_code_claim_ledger.csv` contains the manuscript location, production evidence, audit result, estimate consequence, and recommended action for every substantive claim or implementation check. The separate `manuscript_line_inventory.csv` records all 992 nonblank manuscript lines inspected; formatting-only lines are not repeated in the claim ledger.

## Submission blockers

### 1. Density observation unit is internally inconsistent

`residential_improvements_cleaning.R:113-120` labels the output one row per `(pin, card_num)` but groups only by `pin`. The downstream 500ft file has 3,660 rows and 3,598 distinct building keys. When same-year cards and downstream tiebacks are aggregated to a parcel/project unit, the continuous multifamily FAR coefficient moves from `-0.153` to `-0.057`, and DUPAC moves from `-0.130` to `-0.033`. The binary multifamily DUPAC comparison remains negative and significant, but most other estimates weaken.

This audit does not declare parcel aggregation to be the uniquely correct fix. It establishes that production does not implement the unit it claims and that the headline result depends on that unresolved choice.

### 2. Density geocoding selects surviving 2025 PINs

The density geocoder joins historical construction to `parcel_universe_2025_city.csv`. Of 13,714 eligible construction PINs, 1,229 lack current coordinates, including 493 of 2,627 multifamily PINs. Exact-year historical recovery adds 322 all-construction and 185 multifamily observations inside 500ft. With those rows, all-construction continuous estimates turn positive; multifamily FAR falls in magnitude from `-0.153` to `-0.109`, and DUPAC from `-0.130` to `-0.070`.

Construction-year historical coordinates should be the primary source, with current coordinates only as a documented fallback.

### 3. Active zoning code and cached paper input disagree

The current zoning cleaner removes PD, PMD, and POS districts, but the cached density input includes them. Rebuilding from active source drops 648 of 3,660 all-construction rows and 122 of 701 multifamily rows. Multifamily continuous FAR becomes `-0.0447` (SE `0.0578`) and DUPAC becomes `-0.0638` (SE `0.0554`). Binary multifamily estimates remain strong.

The intended treatment of planned developments must be chosen explicitly. The paper must then be rebuilt from that source rather than retaining cached output from a different rule. Separately, the control is September 2025 zoning rather than construction-vintage zoning.

### 4. Zero-day permit handling is hidden and consequential

Cleaning retains `processing_time >= 0`, but score construction logs only strictly positive days and drops zero-day records. Zero-day permits account for 38.4% of the high-discretion group and 73.7% of the low-discretion group. Positive-only processing times produce the paper's 57.3 versus 26.2 day means; including zeros produces 35.3 versus 6.9 days.

Coding zero-day permits as one day changes the 2022 score Pearson correlation to `0.754` and the 2014 correlation to `0.834`. The high-discretion event-study coefficient changes from `-0.101` to `-0.0577`. The binary density estimates are more stable than the continuous estimates, but neither score definition should be chosen from the resulting significance. The estimand must be justified first.

### 5. Permit outcome does not observe the claimed extensive margin

The event panel reads `building_permits_clean.gpkg`, which is built from the City's issued-permit extract, and counts those rows by application year. All 79,682 relevant permits in 500ft design blocks have an issue year. This means application date is a timing field on observed issued-file permits, not evidence that the dataset covers all submitted applications.

The main estimate is robust to indexing by issue year (`-0.0932` versus `-0.1010`) and to tested status restrictions. That is useful, but it does not solve the estimand problem. The paper can claim fewer observed permits filed in those years, not fewer projects entering permitting or deterrence before issuance, unless a true application universe is obtained.

## Other high-priority findings

- **Construction year:** the residential pipeline selects the minimum reported year over assessor history. Reported year changes for 7,049 PIN-cards, and alternative year rules interact strongly with the unresolved observation unit.
- **Density display:** figure subtitles use the full model, but fitted lines come from a different residual-on-raw-distance regression. The plotted multifamily jumps are `-0.077` and `-0.100`, versus subtitle jumps `-0.267` and `-0.359`.
- **Institutional mechanism:** the manuscript's acknowledgement-letter/10-day-hold description is not what the former ordinance said, and the 2019 code repeal is conflated with Executive Order 2019-2.
- **Turnover sample:** the appendix says blocks are retained regardless of turnover, but unchanged controls in turnover wards are removed. This has almost no effect on the main estimate, so it is a disclosure/code-alignment problem rather than a result driver.
- **Sales arm's-length rule:** production validates sellers, not buyers, and does not identify intrafamily transfers. A stricter audit leaves the estimate essentially unchanged.
- **CTA history:** the code supplies explicit opening dates for only five stations, assigns every other current station an opening date of 1900, and records no closures. The appendix overstates the historical station adjustment.
- **Shared political clusters:** ward-pair clusters share ward endpoints. Endpoint-based two-way clustering makes the sales result insignificant and makes continuous multifamily FAR marginal, while multifamily DUPAC remains significant.
- **Recursive Make lineage:** immediate paper outputs rebuild correctly, but existing deeper outputs can bypass `generic.make`'s recursive recipe. The current graph cannot guarantee that a changed deep input propagates to the paper.

## Checks that passed

- The 2022 score is used for density, rent, and sales; the event study uses the frozen 2006-2014 score.
- The main permit ITT is truly the assigned destination-minus-origin change using both 2014 incumbents.
- The permit 500ft restriction is implemented as census-block centroid distance of at most 500ft to the intended pre-redistricting boundary geometry.
- Largest-area block-to-ward assignment is performed in EPSG:3435.
- A point-on-surface alternative produces a similar permit estimate.
- The permit PPML formula, pre-period controls, fixed effects, clustering variable, coefficients, and outcome-specific observation counts reproduce exactly.
- The stable-incumbent and low-discretion event-study values reproduce exactly.
- Boundary segments and density parcel-to-segment assignments rebuild exactly.
- June 15 is in fact used for density observations when only year built is available, and the timing audit does not identify it as a major result driver.
- The current clean-location rental model retains studios and reproduces `0.03427` (SE `0.00775`, N `240,315`).
- The sales model uses same-year assessor matches for every model row and reproduces `0.01653` (SE `0.00767`, N `51,476`).
- All 37 immediate paper artifacts regenerate identically or with identical extracted text.
- A clean paper-directory build succeeds and produces a 59-page PDF.
- All manuscript citation keys resolve in the bibliography.
- The conceptual model's algebra is correct, and headline percentage transformations match the generated coefficients.

## Recommended decision order

1. Fix the density estimand and data unit: building-card versus parcel/project, construction-year rule, and historical-coordinate source.
2. Decide how zero-day processing times belong in the stringency estimand and rebuild both 2014 and 2022 scores.
3. Decide whether the permit result will be relabeled as observed issued-file permits by application date or rebuilt from a true application universe.
4. Resolve planned-development zoning treatment and rebuild every density descendant from active source.
5. Re-estimate density, rent, sales, and permits with generated-score and shared-ward inference sensitivities clearly separated from the main specification.
6. Repair recursive Make freshness, then run a raw-to-paper clean clone test.
7. Only after the estimates are frozen, revise institutional text, methods, figures, abstract, discussion, and conclusion.

## Audit artifacts

- `manuscript_code_claim_ledger.csv`: claim-by-claim findings and recommended actions.
- `manuscript_line_inventory.csv`: every nonblank manuscript line reviewed.
- `artifact_inventory.csv` and `task_lineage_edges.csv`: paper artifact and lineage map.
- `density_*`, `permit_*`, `rental_*`, `sales_*`, `score_*`, and `inference_*` CSV files: numerical reproductions and sensitivities supporting this report.
- `isolated_rebuild_artifact_comparison.csv`: immediate artifact rebuild comparison.
- `lineage_target_dry_run_status.csv`: deeper-task freshness diagnostics.
"""

REPORT.write_text(report)
