# Recorded construction and matching choices.
EPISODE_YEAR_WINDOW := 2
AUTOMATIC_CARD_BUILDING_GAP := 0.02
SUCCESSOR_POINT_TOLERANCE_FT := 1
SUCCESSOR_LAND_TOLERANCE := 0.005
MAX_DISCOVERY_CONSTRUCTION_YEAR ?= 2026
MIN_CONSTRUCTION_YEAR ?= 1999
PREFERRED_ASSESSMENT_YEAR ?= 2022
FALLBACK_ASSESSMENT_YEAR ?= 2025
HISTORY_START_YEAR ?= 2006
HISTORY_END_YEAR ?= 2022
MIN_INITIAL_AREA_SQFT ?= 1
MAX_DISTANCE_FT ?= 1500
HISTORICAL_EXACT_MATCH_FT ?= 10
HISTORICAL_LOCAL_MATCH_FT ?= 150
HISTORICAL_MAX_BUILDING_GAP ?= 0.10
