all: ../output/commercial_component_overrides.csv \
	../output/commercial_cross_family_decisions.csv \
	../output/commercial_manual_decisions.csv \
	../output/commercial_reported_land_decisions.csv \
	../output/commercial_reviewed_locations.csv \
	../output/commercial_verified_case_review.csv \
	../output/construction_building_types.csv \
	../output/construction_modifications.csv \
	../output/corrected_year_zoning_decisions.csv \
	../output/eligibility_manual_exceptions.csv \
	../output/historical_address_corrections.csv \
	../output/historical_address_matches.csv \
	../output/historical_coordinate_year_corrections.csv \
	../output/residential_additional_candidate_decisions.csv \
	../output/residential_class297_component_overrides.csv \
	../output/residential_overlap_decisions.csv \
	../output/residential_reviewed_building_components.csv \
	../output/residential_reviewed_card_selections.csv \
	../output/residential_reviewed_home_replacements.csv \
	../output/residential_reviewed_parcel_locations.csv \
	../output/residential_reviewed_permit_locations.csv \
	../output/residential_reviewed_source_duplicates.csv \
	../output/residential_reviewed_source_exclusions.csv \
	../output/residential_source_decisions.csv \
	../output/residential_unresolved_source_dispositions.csv

include ../../shared/code/generic.make
