all: paper.pdf

paper.pdf: paper.tex sections/*.tex sections/aldermanic_privilege.bib \
	../tasks/border_pair_FE_bandwidth_path/output/border_pair_fe_bandwidth_path_log_density_dupac_all_main.pdf \
	../tasks/border_pair_FE_bandwidth_path/output/border_pair_fe_bandwidth_path_log_density_dupac_multifamily_main.pdf \
	../tasks/border_pair_FE_bandwidth_path/output/border_pair_fe_bandwidth_path_log_density_far_all_main.pdf \
	../tasks/border_pair_FE_bandwidth_path/output/border_pair_fe_bandwidth_path_log_density_far_multifamily_main.pdf \
	../tasks/border_pair_FE_regressions/output/fe_table_500ft_all_multifamily_zonegroup_segment_year_additive_clust_ward_pair.tex \
	../tasks/border_pair_FE_regressions/output/fe_table_500ft_all_multifamily_zonegroup_segment_year_additive_clust_ward_pair_pruned.tex \
	../tasks/create_alderman_uncertainty_index/output/stage1_regression_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022.tex \
	../tasks/create_alderman_uncertainty_index/output/uncertainty_index_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022.pdf \
	../tasks/density_amenity_balance/output/density_amenity_balance_500ft_all.tex \
	../tasks/density_amenity_balance/output/density_amenity_balance_500ft_multifamily.tex \
	../tasks/density_corner_clean_table/output/fe_table_500ft_all_corner_clean_compare.tex \
	../tasks/density_corner_clean_table/output/fe_table_500ft_multifamily_corner_clean_compare.tex \
	../tasks/event_study_exact_balance/output/permit_exact_balance_summary_1000ft.tex \
	../tasks/event_study_exact_balance/output/redistricting_sample_support_summary_1000ft.tex \
	../tasks/event_study_exact_balance/output/sales_exact_balance_summary_1000ft.tex \
	../tasks/event_study_sales_diagnostics/output/treatment_control_map_2015_1000ft.pdf \
	../tasks/event_study_sales_diagnostics/output/treatment_control_maps_combined_1000ft.pdf \
	../tasks/event_study_sales_diagnostics/output/ward_pair_vertical_13-23_1000ft.pdf \
	../tasks/new_construction_score_density_robustness/output/fe_table_500ft_all_zonegroup_segment_year_additive_clust_ward_pair_low_discretion_residualized_mainoutcomes.tex \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_dupac_500ft_all_donut25ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_dupac_500ft_all_donut50ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_dupac_500ft_multifamily_donut25ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_dupac_500ft_multifamily_donut50ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_far_500ft_all_donut25ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_far_500ft_all_donut50ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_far_500ft_multifamily_donut25ft.pdf \
	../tasks/nonparametric_rd_density_donut/output/nonparametric_rd_density_donut_log_density_far_500ft_multifamily_donut50ft.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_dupac_500ft_all_above_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_dupac_500ft_all_below_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_dupac_500ft_multifamily_above_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_dupac_500ft_multifamily_below_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_far_500ft_all_above_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_far_500ft_all_below_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_far_500ft_multifamily_above_median.pdf \
	../tasks/nonparametric_rd_density_gap_split/output/nonparametric_rd_density_gap_split_log_density_far_500ft_multifamily_below_median.pdf \
	../tasks/nonparametric_rd_density_linear_display/output/nonparametric_rd_density_linear_display_4panel_500ft_all_multifamily_bins5.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_dupac_500ft_all_shift_neg500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_dupac_500ft_all_shift_pos500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_dupac_500ft_multifamily_shift_neg500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_dupac_500ft_multifamily_shift_pos500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_far_500ft_all_shift_neg500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_far_500ft_all_shift_pos500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_far_500ft_multifamily_shift_neg500ft.pdf \
	../tasks/nonparametric_rd_density_placebo/output/nonparametric_rd_density_placebo_log_density_far_500ft_multifamily_shift_pos500ft.pdf \
	../tasks/permit_summary_stats/output/alderman_mean_processing_time_high_vs_low_density.pdf \
	../tasks/permit_summary_stats/output/permit_processing_time_high_vs_low_alderman_summary.tex \
	../tasks/permit_summary_stats/output/permit_processing_time_volume_correlation.tex \
	../tasks/pruned_boundary_maps/output/pruned_boundaries_all_segments_by_era.pdf \
	../tasks/run_event_study_permit/output/did_table_permit_2015_high_discretion_issue_ppml_uniform_1000ft_noctrl_geo_wardpair.tex \
	../tasks/run_event_study_permit/output/event_study_yearly_cohort_2015_high_discretion_issue_ppml_continuous_split_uniform_1000ft_within_block_full_clust_block_geo_wardpair.pdf \
	../tasks/run_event_study_permit/output/event_study_yearly_cohort_2015_high_discretion_issue_ppml_continuous_uniform_1000ft_within_block_full_clust_block_geo_wardpair.pdf \
	../tasks/run_event_study_permit/output/event_study_yearly_cohort_2015_low_discretion_nosigns_issue_ppml_continuous_uniform_1000ft_within_block_full_clust_block_geo_wardpair.pdf \
	../tasks/run_event_study_sales_disaggregate/output/did_table_sales_2015_uniform_1000ft_geo_wardpair_clust_block.tex \
	../tasks/run_event_study_sales_disaggregate/output/event_study_disaggregate_yearly_cohort_2015_continuous_split_uniform_1000ft_amenity_full_geo_wardpair_clust_block.pdf \
	../tasks/run_event_study_sales_disaggregate/output/event_study_disaggregate_yearly_cohort_2015_continuous_uniform_1000ft_amenity_full_geo_wardpair_clust_block.pdf \
	../tasks/strictness_score_map/output/uncertainty_score_map_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022_2022-01.pdf \
	../tasks/summary_stats_new_construction/output/summary_stats.tex \
	../tasks/uncertainty_validation_checks/output/permit_validation_table_uncertainty_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022.tex \
	../tasks/within_ward_strictness/output/low_discretion_falsification_compact_uncertainty_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022.tex \
	../tasks/within_ward_strictness/output/predecessor_successor_scatter_uncertainty_ptfeTRUE_rtfeTRUE_porchTRUE_cafeFALSE_2stage_volLAG1_BOTH_through2022.pdf
	latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make paper.tex

paper.bbl: paper.aux sections/aldermanic_privilege.bib aea.bst
	bibtex paper

../tasks/%:
	@case "$@" in \
		../tasks/*/output/*) \
			task=$$(printf '%s\n' "$@" | sed 's#^\.\./tasks/##; s#/output/.*##'); \
			output=$$(printf '%s\n' "$@" | sed 's#^\.\./tasks/[^/]*/output/#../output/#'); \
			$(MAKE) -C "../tasks/$$task/code" "$$output"; \
			;; \
		*) \
			test -e "$@" || { echo "No paper upstream rule for $@"; false; }; \
			;; \
	esac

clean:
	latexmk -CA
